# Database Settings
spring:
  datasource:
    url: jdbc:h2:mem:h2_jpa_sample;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  redis:
    host: localhost
    port: 6379

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
  thymeleaf:
    cache: false

redis-key:
  ranking:
    search:
      book: ranking:search:book

api:
  kakao:
    url: https://dapi.kakao.com
    rest-api-key: KakaoAK bc2d447fd7692a927df6b0989ff2fe81
  naver:
    url: https://openapi.naver.com
    client-id: ITZxT4y6gmmq2DUnx1tQ
    client-secret: uIugXfqEyW